INSERT INTO usr(name) VALUES ('gfisher');
INSERT INTO usr(name) VALUES ('ddelaney');
INSERT INTO usr(name) VALUES ('jjacobson');
INSERT INTO usr(name) VALUES ('gstringfellow');
INSERT INTO usr(name) VALUES ('dsloane');
INSERT INTO usr(name) VALUES ('scha');
INSERT INTO project(name, approver_id) VALUES ('KCLS', 1);
INSERT INTO project(name, approver_id) VALUES ('Choice', 2);
INSERT INTO lineitemtype(name) VALUES ('Mileage');
INSERT INTO lineitemtype(name) VALUES ('Per Diem');
INSERT INTO lineitemtype(name) VALUES ('Lodging');
INSERT INTO lineitemtype(name) VALUES ('Travel');
INSERT INTO lineitemtype(name) VALUES ('Meals');
INSERT INTO lineitemtype(name) VALUES ('Entertainment');
INSERT INTO lineitemtype(name) VALUES ('Parking');
INSERT INTO lineitemtype(name) VALUES ('Other');
INSERT INTO lineitem(datmoney, type_id) VALUES (25.00, 1);
INSERT INTO lineitem(datmoney, type_id) VALUES (15.00, 2);
INSERT INTO lineitem(datmoney, type_id) VALUES (20.00, 5);
INSERT INTO lineitem(datmoney, type_id) VALUES (37.10, 5);
INSERT INTO lineitem(datmoney, type_id) VALUES (1450.19, 7);
INSERT INTO lineitem(datmoney, type_id) VALUES (110.19, 3);
INSERT INTO lineitem(datmoney, type_id) VALUES (10.98, 5);
INSERT INTO expensereport(name, project_id, user_id) VALUES ('Seattle Trip for KCLS', 1, 5);
INSERT INTO expensereport(name, project_id, user_id) VALUES ('Traveled to Arizona for Choice', 2, 3);
INSERT INTO expensereport(name, project_id, user_id) VALUES ('Donuts for KCLS', 1, 5);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (1,1);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (1,2);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (1,3);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (2,4);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (2,5);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (2,6);
INSERT INTO expensereport_lineitem(expensereport_id, lineitems_id) VALUES (3,7);